### Логін як acme_hr
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "acme_hr",
  "password": "password123"
}

###

### Отримати всі заявки на вакансії acme_hr
GET http://localhost:3000/api/applications/employer